import { defineConfig, devices } from '@playwright/test';

const PORT = 4321;

export default defineConfig({
  testDir: 'tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  reporter: [['list'], ['json', { outputFile: 'test-results/results.json' }], ['html', { open: 'never' }]],
  // Baselines are per platform: macOS locally, Linux in CI (generated by CI on first run).
  snapshotPathTemplate: '{testDir}/__screenshots__/{platform}/{projectName}/{arg}{ext}',
  expect: { toHaveScreenshot: { maxDiffPixelRatio: 0.01, animations: 'disabled' } },
  use: {
    baseURL: `http://127.0.0.1:${PORT}`,
    trace: 'retain-on-failure',
  },
  projects: [
    { name: 'desktop', use: { ...devices['Desktop Chrome'], viewport: { width: 1440, height: 900 } } },
    // PDF and leak-check specs are browser-independent, so they only run on desktop.
    { name: 'iphone-13', use: { ...devices['iPhone 13'] }, testIgnore: /(pdf|leak-check)\.spec/ },
    { name: 'pixel-7', use: { ...devices['Pixel 7'] }, testIgnore: /(pdf|leak-check)\.spec/ },
  ],
  webServer: {
    command: `npx tsx scripts/serve.ts`,
    env: { PORT: String(PORT) },
    url: `http://127.0.0.1:${PORT}/`,
    reuseExistingServer: !process.env.CI,
  },
});
